-- IAM-US-009: Provision the 13 baseline roles with the RBAC permission
-- matrix. The BRD's own RBAC matrix (Section 8, per the FRS's repeated
-- cross-reference) is a separate document not available in this
-- repository — this seed is a provisional, defensible matrix built from
-- the FRS's own persona frequency across all 186 user stories and standard
-- least-privilege conventions, not a transcription of the real BRD table.
-- Flagged for Product/BRD sign-off; expect this migration's data (not its
-- shape) to be superseded once the real matrix is available.
--
-- 9 of the 13 roles already exist (V6__seed_default_roles.sql); this adds
-- the remaining 4 baseline roles the FRS names at meaningful frequency but
-- that were never seeded: Compliance Officer (AUDT oversight), Reporting
-- Analyst (RPTA), Billing Administrator (PBIL), Occupational Health
-- Practitioner (OCCH) — the latter three anticipate modules not yet built,
-- deliberately: the whole point of baseline roles is that they're ready
-- before a tenant activates the module, not seeded reactively afterward.
INSERT INTO roles (id, name) VALUES
    (gen_random_uuid(), 'Compliance Officer'),
    (gen_random_uuid(), 'Reporting Analyst'),
    (gen_random_uuid(), 'Billing Administrator'),
    (gen_random_uuid(), 'Occupational Health Practitioner');

-- One permission code per (module, level) — VIEW and MANAGE only. Two
-- tiers, not full CRUD: no module in this codebase distinguishes finer
-- than that today, and MANAGE is treated as a superset of VIEW at
-- evaluation time (PermissionService), not seeded as two separate grants
-- per role. A module/level with no role granted it (e.g. every SADM/IAM
-- code below MANAGE) is reachable by nobody but ORG_ADMIN — deliberate,
-- not an oversight.
INSERT INTO permissions (code) VALUES
    ('SADM:VIEW'), ('SADM:MANAGE'),
    ('AUDT:VIEW'), ('AUDT:MANAGE'),
    ('IAM:VIEW'), ('IAM:MANAGE'),
    ('PREG:VIEW'), ('PREG:MANAGE'),
    ('RECQ:VIEW'), ('RECQ:MANAGE'),
    ('APPT:VIEW'), ('APPT:MANAGE'),
    ('PHRM:VIEW'), ('PHRM:MANAGE'),
    ('BIOM:VIEW'), ('BIOM:MANAGE'),
    ('CSAC:VIEW'), ('CSAC:MANAGE'),
    ('CSCC:VIEW'), ('CSCC:MANAGE'),
    ('CSMC:VIEW'), ('CSMC:MANAGE'),
    ('RPTA:VIEW'), ('RPTA:MANAGE'),
    ('MHWA:VIEW'), ('MHWA:MANAGE'),
    ('OCCH:VIEW'), ('OCCH:MANAGE'),
    ('CASE:VIEW'), ('CASE:MANAGE'),
    ('ASMT:VIEW'), ('ASMT:MANAGE'),
    ('TELE:VIEW'), ('TELE:MANAGE'),
    ('PBIL:VIEW'), ('PBIL:MANAGE'),
    ('MENV:VIEW'), ('MENV:MANAGE'),
    ('CSOC:VIEW'), ('CSOC:MANAGE');

-- The matrix itself: (role name, permission code) pairs, resolved to the
-- real generated UUIDs by name/code rather than hardcoded — same pattern
-- as every other seed in this codebase that can't know IDs in advance.
-- Absence from this list is the explicit no-access case IAM-US-009's own
-- AC3 requires: PermissionService denies by default, it doesn't need a
-- negative row to deny.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM (VALUES
    ('ORG_ADMIN', 'SADM:MANAGE'),
    ('ORG_ADMIN', 'AUDT:MANAGE'),
    ('ORG_ADMIN', 'IAM:MANAGE'),
    ('ORG_ADMIN', 'PREG:MANAGE'),
    ('ORG_ADMIN', 'RECQ:MANAGE'),
    ('ORG_ADMIN', 'APPT:MANAGE'),
    ('ORG_ADMIN', 'PHRM:MANAGE'),
    ('ORG_ADMIN', 'BIOM:MANAGE'),
    ('ORG_ADMIN', 'CSAC:MANAGE'),
    ('ORG_ADMIN', 'CSCC:MANAGE'),
    ('ORG_ADMIN', 'CSMC:MANAGE'),
    ('ORG_ADMIN', 'RPTA:MANAGE'),
    ('ORG_ADMIN', 'MHWA:MANAGE'),
    ('ORG_ADMIN', 'OCCH:MANAGE'),
    ('ORG_ADMIN', 'CASE:MANAGE'),
    ('ORG_ADMIN', 'ASMT:MANAGE'),
    ('ORG_ADMIN', 'TELE:MANAGE'),
    ('ORG_ADMIN', 'PBIL:MANAGE'),
    ('ORG_ADMIN', 'MENV:MANAGE'),
    ('ORG_ADMIN', 'CSOC:MANAGE'),
    ('Facility Manager', 'AUDT:VIEW'),
    ('Facility Manager', 'PREG:VIEW'),
    ('Facility Manager', 'RECQ:MANAGE'),
    ('Facility Manager', 'APPT:MANAGE'),
    ('Facility Manager', 'PHRM:VIEW'),
    ('Facility Manager', 'BIOM:VIEW'),
    ('Facility Manager', 'CSAC:VIEW'),
    ('Facility Manager', 'CSCC:VIEW'),
    ('Facility Manager', 'CSMC:VIEW'),
    ('Facility Manager', 'OCCH:VIEW'),
    ('Facility Manager', 'RPTA:VIEW'),
    ('Facility Manager', 'MHWA:VIEW'),
    ('Facility Manager', 'CASE:VIEW'),
    ('Facility Manager', 'ASMT:VIEW'),
    ('Facility Manager', 'TELE:VIEW'),
    ('Facility Manager', 'MENV:VIEW'),
    ('Facility Manager', 'CSOC:VIEW'),
    ('Admin Staff', 'PREG:MANAGE'),
    ('Admin Staff', 'RECQ:MANAGE'),
    ('Admin Staff', 'APPT:MANAGE'),
    ('Admin Staff', 'BIOM:MANAGE'),
    ('Doctor', 'PREG:VIEW'),
    ('Doctor', 'RECQ:VIEW'),
    ('Doctor', 'APPT:VIEW'),
    ('Doctor', 'PHRM:MANAGE'),
    ('Doctor', 'BIOM:VIEW'),
    ('Doctor', 'CSAC:MANAGE'),
    ('Doctor', 'CSCC:MANAGE'),
    ('Doctor', 'CSMC:MANAGE'),
    ('Doctor', 'OCCH:MANAGE'),
    ('Doctor', 'CASE:MANAGE'),
    ('Doctor', 'ASMT:MANAGE'),
    ('Doctor', 'TELE:MANAGE'),
    ('Doctor', 'RPTA:VIEW'),
    ('Doctor', 'MHWA:VIEW'),
    ('Doctor', 'MENV:VIEW'),
    ('Doctor', 'CSOC:VIEW'),
    ('Professional Nurse', 'PREG:VIEW'),
    ('Professional Nurse', 'RECQ:VIEW'),
    ('Professional Nurse', 'APPT:VIEW'),
    ('Professional Nurse', 'PHRM:MANAGE'),
    ('Professional Nurse', 'BIOM:VIEW'),
    ('Professional Nurse', 'CSAC:MANAGE'),
    ('Professional Nurse', 'CSCC:MANAGE'),
    ('Professional Nurse', 'CSMC:MANAGE'),
    ('Professional Nurse', 'OCCH:MANAGE'),
    ('Professional Nurse', 'CASE:MANAGE'),
    ('Professional Nurse', 'ASMT:MANAGE'),
    ('Professional Nurse', 'TELE:MANAGE'),
    ('Professional Nurse', 'RPTA:VIEW'),
    ('Professional Nurse', 'MHWA:VIEW'),
    ('Professional Nurse', 'MENV:VIEW'),
    ('Professional Nurse', 'CSOC:VIEW'),
    ('Clinician', 'PREG:VIEW'),
    ('Clinician', 'RECQ:VIEW'),
    ('Clinician', 'APPT:VIEW'),
    ('Clinician', 'PHRM:VIEW'),
    ('Clinician', 'BIOM:VIEW'),
    ('Clinician', 'CSAC:MANAGE'),
    ('Clinician', 'CSCC:MANAGE'),
    ('Clinician', 'CSMC:MANAGE'),
    ('Clinician', 'OCCH:MANAGE'),
    ('Clinician', 'CASE:VIEW'),
    ('Clinician', 'ASMT:MANAGE'),
    ('Clinician', 'TELE:VIEW'),
    ('Clinician', 'RPTA:VIEW'),
    ('Clinician', 'MHWA:VIEW'),
    ('Clinician', 'MENV:VIEW'),
    ('Clinician', 'CSOC:VIEW'),
    ('Pharmacist', 'PREG:VIEW'),
    ('Pharmacist', 'RECQ:VIEW'),
    ('Pharmacist', 'PHRM:MANAGE'),
    ('Queue Marshall', 'RECQ:MANAGE'),
    ('Queue Marshall', 'APPT:VIEW'),
    ('Queue Marshall', 'PREG:VIEW'),
    ('Social Worker', 'CASE:MANAGE'),
    ('Social Worker', 'CSMC:VIEW'),
    ('Social Worker', 'PREG:VIEW'),
    ('Social Worker', 'RECQ:VIEW'),
    ('Social Worker', 'CSOC:VIEW'),
    ('Compliance Officer', 'SADM:VIEW'),
    ('Compliance Officer', 'AUDT:VIEW'),
    ('Compliance Officer', 'IAM:VIEW'),
    ('Compliance Officer', 'PREG:VIEW'),
    ('Compliance Officer', 'RECQ:VIEW'),
    ('Compliance Officer', 'APPT:VIEW'),
    ('Compliance Officer', 'PHRM:VIEW'),
    ('Compliance Officer', 'BIOM:VIEW'),
    ('Compliance Officer', 'CSAC:VIEW'),
    ('Compliance Officer', 'CSCC:VIEW'),
    ('Compliance Officer', 'CSMC:VIEW'),
    ('Compliance Officer', 'RPTA:VIEW'),
    ('Compliance Officer', 'MHWA:VIEW'),
    ('Compliance Officer', 'OCCH:VIEW'),
    ('Compliance Officer', 'CASE:VIEW'),
    ('Compliance Officer', 'ASMT:VIEW'),
    ('Compliance Officer', 'TELE:VIEW'),
    ('Compliance Officer', 'PBIL:VIEW'),
    ('Compliance Officer', 'MENV:VIEW'),
    ('Compliance Officer', 'CSOC:VIEW'),
    ('Reporting Analyst', 'RPTA:MANAGE'),
    ('Reporting Analyst', 'PREG:VIEW'),
    ('Reporting Analyst', 'RECQ:VIEW'),
    ('Reporting Analyst', 'APPT:VIEW'),
    ('Reporting Analyst', 'PHRM:VIEW'),
    ('Reporting Analyst', 'BIOM:VIEW'),
    ('Reporting Analyst', 'CSAC:VIEW'),
    ('Reporting Analyst', 'CSCC:VIEW'),
    ('Reporting Analyst', 'CSMC:VIEW'),
    ('Reporting Analyst', 'OCCH:VIEW'),
    ('Reporting Analyst', 'CASE:VIEW'),
    ('Reporting Analyst', 'ASMT:VIEW'),
    ('Reporting Analyst', 'TELE:VIEW'),
    ('Reporting Analyst', 'MHWA:VIEW'),
    ('Reporting Analyst', 'PBIL:VIEW'),
    ('Reporting Analyst', 'MENV:VIEW'),
    ('Reporting Analyst', 'CSOC:VIEW'),
    ('Billing Administrator', 'PBIL:MANAGE'),
    ('Billing Administrator', 'PREG:VIEW'),
    ('Billing Administrator', 'APPT:VIEW'),
    ('Billing Administrator', 'PHRM:VIEW'),
    ('Occupational Health Practitioner', 'OCCH:MANAGE'),
    ('Occupational Health Practitioner', 'CSAC:MANAGE'),
    ('Occupational Health Practitioner', 'PREG:VIEW'),
    ('Occupational Health Practitioner', 'RECQ:VIEW'),
    ('Occupational Health Practitioner', 'APPT:VIEW'),
    ('Occupational Health Practitioner', 'PHRM:VIEW'),
    ('Occupational Health Practitioner', 'BIOM:VIEW'),
    ('Occupational Health Practitioner', 'RPTA:VIEW')
) AS matrix(role_name, permission_code)
JOIN roles r ON r.name = matrix.role_name
JOIN permissions p ON p.code = matrix.permission_code;
