// Run against a local Vite server. API fixtures contain synthetic patients only.
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || "chrome" });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
const token = `test.${Buffer.from(JSON.stringify({ roles: ["Professional Nurse"] })).toString("base64url")}.test`;
await context.addInitScript(token => {
  sessionStorage.setItem("ulwembu.tenantToken", token);
  sessionStorage.setItem("ulwembu.tenantSlug", "vitals-test");
  window.print = () => {};
}, token);
const patient = { id: "patient-1", firstName: "Test", lastName: "Patient", mpiNumber: "TEST-001", dateOfBirth: "1990-01-01", gender: "FEMALE", citizenshipStatus: "SA_CITIZEN", idNumber: "TEST", address: "Test clinic", contactNumber: "0000000000", medicalAidProvider: null, medicalAidNumber: null, passportNumber: null, passportExpiry: null, createdAt: "2026-09-08T10:00:00Z", archived: false };
let saved, submitted;
await context.route("**/api/**", async route => {
  const path = new URL(route.request().url()).pathname;
  if (!path.startsWith("/api/")) return route.continue();
  let result = { items: [] };
  if (path.endsWith("/auth/me")) result = { id: "nurse-1", firstName: "Test", lastName: "Nurse", email: "test@example.invalid" };
  else if (path.endsWith("/organization")) result = { displayName: "Test Clinic", shortName: "Test", slug: "vitals-test" };
  else if (path === "/api/v1/patients/patient-1") result = patient;
  else if (path.endsWith("/visits/visit-1/triage") && route.request().method() === "POST") {
    submitted = route.request().postDataJSON();
    saved = { ...submitted, id: "reading-1", visitId: "visit-1", status: "ACTIVE", scoringProfile: "ADULT", tewsScore: 1, scoringVersion: "SATS-DRAFT-2026.2", calculatedColour: "GREEN", finalColour: "GREEN", capturedByUserId: "nurse-1", observedAt: "2026-09-08T10:00:00Z", recordedAt: "2026-09-08T10:00:00Z", additionalObservations: { ...submitted.additionalObservations, bmi: 25.1 } };
    result = saved;
  } else if (path.endsWith("/visits/visit-1/triage")) result = { items: saved ? [saved] : [] };
  else if (path.endsWith("/patients/patient-1/vitals")) result = { items: saved ? [{ assessment: saved, capturedByName: "Test Nurse" }] : [], page: 0, pageSize: 10, totalElements: saved ? 1 : 0, totalPages: saved ? 1 : 0 };
  else if (path.endsWith("/triage/reading-1")) result = { assessment: saved, capturedByName: "Test Nurse", patientName: "Test Patient", patientMpi: "TEST-001" };
  await route.fulfill({ json: result });
});
const page = await context.newPage();
page.setDefaultTimeout(10000);
const errors = [];
page.on("pageerror", error => errors.push(error.message));
try {
  await page.goto(`${process.env.VITALS_UI_URL || "http://127.0.0.1:5178"}/app/patients/patient-1?visitId=visit-1`);
  await page.getByRole("button", { name: "Take vitals", exact: true }).last().click();
  for (const [label, value] of [[/Respiratory rate/, "18"], [/Heart rate/, "80"], [/Systolic BP/, "120"], [/Diastolic BP/, "80"], [/Temperature/, "37"], [/SpO2/, "98"]]) await page.getByLabel(label).fill(value);
  await page.getByLabel(/^AVPU/).selectOption("ALERT");
  await page.getByLabel(/^Mobility/).selectOption("WALKING");
  await page.getByRole("button", { name: "Save vitals", exact: true }).click();
  await page.getByRole("alert").filter({ hasText: "Select whether an injury" }).waitFor();
  assert.equal(submitted, undefined);
  await page.getByLabel("Injury within the past 48 hours").selectOption("yes");
  await page.getByRole("spinbutton", { name: "Weight (kg)", exact: true }).fill("-1");
  await page.getByRole("button", { name: "Save vitals", exact: true }).click();
  await page.getByRole("alert").filter({ hasText: "numbers greater than zero" }).waitFor();
  assert.equal(submitted, undefined);
  await page.getByRole("spinbutton", { name: "Weight (kg)", exact: true }).fill("72.5");
  await page.getByLabel("Height / length (cm)").fill("170");
  await page.getByLabel("Blood glucose (mmol/L)").fill("5.6");
  await page.getByLabel("Haemoglobin (g/dL)").fill("12.3");
  await page.getByText("Calculated BMI:").waitFor();
  await page.locator("summary").filter({ hasText: "Urine dipstick" }).click();
  await page.getByLabel("Urine protein", { exact: true }).selectOption("NEGATIVE");
  await page.getByLabel("Urine ketones", { exact: true }).selectOption("TRACE");
  await page.getByLabel("Urine pregnancy test", { exact: true }).selectOption("INDETERMINATE");
  await mkdir("test-results", { recursive: true });
  await page.getByText("Additional measurements", { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: "test-results/vitals-capture.png", fullPage: true });
  await page.getByRole("button", { name: "Save vitals", exact: true }).click();
  await page.getByRole("button", { name: "Take new reading", exact: true }).waitFor();
  assert.equal(submitted.additionalObservations.weightKg, 72.5);
  assert.equal(submitted.additionalObservations.traumaPresent, true);
  assert.equal(submitted.additionalObservations.urineProtein, "NEGATIVE");
  assert.equal(submitted.additionalObservations.urineGlucose, null);
  assert.equal(submitted.additionalObservations.pregnancyTest, "INDETERMINATE");
  await page.getByRole("tab", { name: "Vitals", exact: true }).click();
  await page.getByRole("heading", { name: "Vitals history", exact: true }).waitFor();
  await page.getByRole("button").filter({ hasText: "Captured" }).last().waitFor();
  await page.screenshot({ path: "test-results/vitals-history-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/vitals-history-mobile.png", fullPage: true });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
  assert.equal(overflow, false, "Mobile page must not scroll horizontally");
  await page.getByRole("button").filter({ hasText: "Captured" }).last().click();
  await page.getByRole("dialog").waitFor();
  assert.equal(await page.evaluate(() => document.activeElement?.getAttribute("aria-label")), "Close");
  await page.keyboard.press("Tab");
  assert.equal(await page.evaluate(() => document.activeElement?.getAttribute("aria-label")), "Print this vitals reading");
  await page.getByRole("dialog").getByText("Indeterminate", { exact: true }).waitFor();
  assert.equal((await page.getByRole("dialog").innerText()).includes("undefined"), false);
  await page.screenshot({ path: "test-results/vitals-detail-mobile.png", fullPage: true });
  await page.keyboard.press("Escape");
  await page.getByRole("dialog").waitFor({ state: "detached" });
  await page.goto(`${process.env.VITALS_UI_URL || "http://127.0.0.1:5178"}/print/vitals/reading-1`);
  await page.getByText("Indeterminate", { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log("PASS: capture validation, payload values, optional/negative results, history, mobile layout, details and print.");
} catch (error) {
  console.error("Browser errors:", errors);
  console.error("Page:", (await page.locator("body").innerText()).slice(0, 3000));
  throw error;
} finally { await browser.close(); }
